// @ts-check

/**
 * The documentation sidebar.
 *
 * Ordered explicitly rather than autogenerated: the reading order is an
 * argument — what this fork is, then how to run it, then what it adds, then
 * how to operate it — and an explicit list is where that argument is visible.
 * `sidebar_position` in each file's front matter is kept in sync so a page
 * opened on its own still reports where it sits.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  documentation: [
    'index',
    'about-this-fork',
    'getting-started',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'configuration',
        'http-endpoints',
      ],
    },
    {
      type: 'category',
      label: 'Added by this fork',
      collapsed: false,
      items: [
        'tile-matrix-sets',
        'ogc-api-tiles',
        'layered-cache',
      ],
    },
    {
      type: 'category',
      label: 'Operating',
      collapsed: false,
      items: [
        'cache-seeding-and-purging',
        'debugging',
        'logging',
      ],
    },
  ],
};

export default sidebars;
